# Generated by Django 3.2.16 on 2025-09-24 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Производитель')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('transmission', models.CharField(max_length=100, verbose_name='Коробка передач')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег, км')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='bid.equipment', verbose_name='Единица техники')),
            ],
            options={
                'verbose_name': 'Характеристики техники',
                'verbose_name_plural': 'Характеристики техники',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='bid.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='bid.Tag', verbose_name='Теги'),
        ),
    ]
