# Generated by Django 3.2.16 on 2025-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20250924_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='Изображение техники'),
        ),
    ]
