# Generated by Django 3.2.16 on 2025-09-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_equipment_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-time_create'], 'permissions': [('can_publish_equipment', 'Может публиковать оборудование')], 'verbose_name': 'Единица техники', 'verbose_name_plural': 'Единицы техники'},
        ),
    ]
