# Generated by Django 3.2.16 on 2025-09-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_alter_equipment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-time_create'], 'permissions': [('can_publish_equipment', 'Может публиковать оборудование'), ('can_manage_equipment', 'Может управлять оборудованием'), ('can_view_equipment_analytics', 'Может просматривать аналитику оборудования')], 'verbose_name': 'Единица техники', 'verbose_name_plural': 'Единицы техники'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'permissions': [('can_manage_manufacturers', 'Может управлять производителями')], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'permissions': [('can_manage_tags', 'Может управлять тегами')], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
